# Generated by Django 5.0.3 on 2024-04-03 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familiya', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123456789'. Up to 15 digits", regex='^\\+?998?\\d{9,13}$')])),
                ('xabar', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150)),
                ('malumot', models.TextField(max_length=555)),
                ('rasm', models.ImageField(upload_to='project_images/')),
                ('url', models.URLField()),
                ('github_url', models.URLField()),
            ],
        ),
    ]
